# Generated by Django 3.2.2 on 2021-06-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='foods',
            name='ftag1',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='ftag1', to='testapp.tags'),
        ),
        migrations.AddField(
            model_name='foods',
            name='ftag2',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='ftag2', to='testapp.tags'),
        ),
    ]
