# Generated by Django 3.2.2 on 2021-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210608_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='ftag1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='foods',
            name='ftag2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
