# Generated by Django 3.2.2 on 2021-06-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210608_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='fimg2',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='fimg3',
        ),
    ]
