# Generated by Django 3.2.2 on 2021-06-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210608_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdata', models.CharField(max_length=250)),
                ('cemail', models.EmailField(max_length=254)),
                ('cdate', models.DateField(auto_now_add=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testapp.foods')),
            ],
        ),
    ]
