# Generated by Django 3.2.2 on 2021-06-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='food_name',
            field=models.CharField(default='testing', max_length=50),
            preserve_default=False,
        ),
    ]
