# Generated by Django 3.2.2 on 2021-06-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
