# Generated by Django 3.2.2 on 2021-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_validated',
            field=models.CharField(default='y', max_length=1),
            preserve_default=False,
        ),
    ]
