# Generated by Django 3.2.2 on 2021-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_alter_otp_odate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
