# Generated by Django 3.2.2 on 2021-07-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20210621_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_accepted',
            field=models.CharField(default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='order_delivered',
            field=models.CharField(default='y', max_length=1),
            preserve_default=False,
        ),
    ]
