# Generated by Django 3.2.2 on 2021-07-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_auto_20210704_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_accepted',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_delivered',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
